vich_uploader:
    db_driver: orm

    metadata:
        type: attibute

    mappings:
        recipe:
            uri_prefix: /images/recipe
            upload_destination: "%kernel.project_dir%/public/images/recipe"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
